Repository farcasterxyz/auth-monorepo, pull requests merged in 2024-01, with the labels that each got.

#18 refactor: split up hooks
  packages/connect/README.md
  packages/connect/src/actions/app/connect.test.ts
  packages/connect/src/actions/app/status.test.ts
  packages/connect/src/actions/app/verifySignInMessage.test.ts
  packages/connect/src/actions/app/watchStatus.test.ts
  packages/connect/src/actions/app/watchStatus.ts
  packages/connect/src/clients/createAppClient.test.ts
  packages/connect/src/clients/createAuthClient.test.ts
  packages/connect/src/clients/createClient.test.ts
  packages/connect/src/clients/createClient.ts
  packages/react/src/hooks/useAppClient.ts
  packages/react/src/hooks/useConnect.ts
  packages/react/src/hooks/useSignIn.ts
  packages/react/src/hooks/useVerifySignInMessage.ts
  packages/react/src/hooks/useWatchStatus.ts
Labels: chore

#20 fix: override defaults with args
  packages/react/src/hooks/useAppClient.ts
  packages/react/src/hooks/useSignIn.ts
  packages/react/src/hooks/useWatchStatus.ts
Labels: bug

#22 feat: optional userData parameters
  apps/relay/src/schemas.ts
  apps/relay/src/server.test.ts
  packages/connect/.changeset/odd-laws-sneeze.md
  packages/connect/src/actions/auth/authenticate.ts
Labels: feature

#23 chore: release connect@0.0.3
  .changeset/hungry-llamas-remember.md
  apps/relay/CHANGELOG.md
  apps/relay/package.json
  packages/connect/.changeset/README.md
  packages/connect/.changeset/config.json
  packages/connect/.changeset/odd-laws-sneeze.md
  packages/connect/CHANGELOG.md
  packages/connect/package.json
  packages/react/CHANGELOG.md
  packages/react/package.json
Labels: chore

#24 refactor: split up connect components
  packages/react/src/components/ConnectButton/ConnectButton.tsx
  packages/react/src/components/ConnectButton/index.ts
  packages/react/src/components/Demo/Demo.tsx
  packages/react/src/components/ErrorMessage/ErrorMessage.tsx
  packages/react/src/components/ErrorMessage/index.ts
  packages/react/src/components/ProfileButton/ProfileButton.tsx
  packages/react/src/components/ProfileButton/index.ts
  packages/react/src/components/QRCodeDialog/QRCodeDialog.tsx
  packages/react/src/components/QRCodeDialog/index.tsx
  packages/react/src/components/SignInButton/SignInButton.tsx
  packages/react/src/hooks/useConnect.ts
  packages/react/src/hooks/useSignIn.ts
  packages/react/src/hooks/useVerifySignInMessage.ts
  packages/react/src/hooks/useWatchStatus.ts
Labels: chore

#26 feat: extract provider and context
  packages/react/src/components/ConnectButton/ConnectButton.tsx
  packages/react/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/react/src/components/ConnectKitProvider/index.ts
  packages/react/src/components/Demo/Demo.tsx
  packages/react/src/hooks/useAppClient.ts
  packages/react/src/hooks/useConnect.ts
  packages/react/src/hooks/useConnectKitContext.ts
  packages/react/src/hooks/useSignIn.ts
  packages/react/src/hooks/useUserData.ts
  packages/react/src/hooks/useVerifySignInMessage.ts
  packages/react/src/hooks/useWatchStatus.ts
Labels: feature

#27 chore: rename package connect-kit
  packages/connect-kit/.eslintrc.cjs
  packages/connect-kit/.gitignore
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/README.md
  packages/connect-kit/index.html
  packages/connect-kit/package.json
  packages/connect-kit/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-kit/src/components/ConnectButton/index.ts
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/src/components/ConnectKitProvider/index.ts
  packages/connect-kit/src/components/Demo/Demo.tsx
  packages/connect-kit/src/components/Demo/index.ts
  packages/connect-kit/src/components/Dialog/Dialog.css.ts
  packages/connect-kit/src/components/Dialog/Dialog.tsx
  packages/connect-kit/src/components/Dialog/FocusTrap.tsx
  packages/connect-kit/src/components/Dialog/index.ts
  packages/connect-kit/src/components/ErrorMessage/ErrorMessage.tsx
  packages/connect-kit/src/components/ErrorMessage/index.ts
  packages/connect-kit/src/components/ProfileButton/ProfileButton.tsx
  packages/connect-kit/src/components/ProfileButton/index.ts
  packages/connect-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
  packages/connect-kit/src/components/QRCodeDialog/index.tsx
  packages/connect-kit/src/components/SignInButton/SignInButton.tsx
  packages/connect-kit/src/components/SignInButton/index.ts
  packages/connect-kit/src/components/index.ts
  packages/connect-kit/src/components/styles.css.ts
  packages/connect-kit/src/demo.tsx
  packages/connect-kit/src/hooks/index.ts
  packages/connect-kit/src/hooks/useAppClient.ts
  packages/connect-kit/src/hooks/useConnect.ts
  packages/connect-kit/src/hooks/useConnectKitContext.ts
  packages/connect-kit/src/hooks/useSignIn.ts
  packages/connect-kit/src/hooks/useUserData.ts
  packages/connect-kit/src/hooks/useVerifySignInMessage.ts
  packages/connect-kit/src/hooks/useWatchStatus.ts
  packages/connect-kit/src/index.ts
  packages/connect-kit/src/utils.ts
  packages/connect-kit/src/vite-env.d.ts
  packages/connect-kit/tsconfig.json
  packages/connect-kit/tsconfig.node.json
  packages/connect-kit/vite.config.ts
  packages/react/README.md
Labels: chore

#28 chore: add changeset
  .changeset/slimy-beans-applaud.md
Labels: chore

#29 chore: publish connect-kit@0.0.2
  .changeset/slimy-beans-applaud.md
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect-kit/src/components/ConnectKitProvider/index.ts
  packages/connect-kit/src/components/index.ts
  packages/connect-kit/src/hooks/index.ts
  packages/connect-kit/src/hooks/useConnect.ts
  packages/connect-kit/src/hooks/useSignIn.ts
  packages/connect-kit/src/hooks/useVerifySignInMessage.ts
  packages/connect-kit/src/hooks/useWatchStatus.ts
  packages/connect-kit/tsconfig.node.json
  packages/connect-kit/vite.config.ts
  packages/connect/CHANGELOG.md
  packages/connect/package.json
Labels: chore

#30 fix: fix package dist
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
Labels: chore

#31 chore: add css to package, release 0.0.4
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
Labels: chore

#32 fix: bundle types, publish v0.0.5
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/vite.config.ts
  yarn.lock
Labels: chore

#33 fix: roll up types, publish v0.0.6
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect-kit/vite.config.ts
Labels: chore

#34 fix: remove @farcaster/core dependency
  .changeset/spotty-chefs-tie.md
  packages/connect/package.json
  packages/connect/src/clients/ethereum/viem.ts
  packages/connect/src/contracts/idRegistry.ts
  yarn.lock
Labels: chore

#35 chore: publish connect@0.0.5, connect-kit@0.0.7
  .changeset/spotty-chefs-tie.md
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect/CHANGELOG.md
  packages/connect/package.json
Labels: chore

#36 chore: prune bundles
  .changeset/great-jars-hammer.md
  package.json
  packages/connect-kit/vite.config.ts
  packages/connect/package.json
  yarn.lock
Labels: chore

#37 chore: publish connect@0.0.6 and connect-kit@0.0.8
  .changeset/great-jars-hammer.md
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect/CHANGELOG.md
  packages/connect/package.json
Labels: chore

#38 chore: lowercase URI/URL
  .changeset/stale-carrots-wave.md
  packages/connect-kit/src/components/ConnectButton/ConnectButton.tsx
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/src/components/Demo/Demo.tsx
  packages/connect-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
  packages/connect-kit/src/hooks/useConnect.ts
  packages/connect-kit/src/hooks/useSignIn.ts
  packages/connect-kit/src/hooks/useWatchStatus.ts
  packages/connect/scripts/console.ts
  packages/connect/src/actions/app/connect.ts
  packages/connect/src/actions/app/status.test.ts
  packages/connect/src/actions/app/watchStatus.ts
  packages/connect/src/actions/auth/authenticate.test.ts
  packages/connect/src/actions/auth/buildSignInMessage.test.ts
  packages/connect/src/actions/auth/parseSignInURI.test.ts
  packages/connect/src/clients/createAppClient.test.ts
  packages/connect/src/clients/createAuthClient.test.ts
  packages/connect/src/clients/createClient.test.ts
  packages/connect/src/clients/createClient.ts
  packages/connect/src/clients/transports/http.test.ts
  packages/connect/src/clients/transports/http.ts
Labels: chore

#39 chore: use Warpcast URLs
  .changeset/six-eyes-grab.md
  apps/relay/package.json
  apps/relay/src/env.ts
  apps/relay/src/handlers.ts
  apps/relay/src/server.test.ts
  packages/connect/src/actions/app/status.test.ts
  packages/connect/src/actions/auth/authenticate.test.ts
  packages/connect/src/actions/auth/parseSignInURI.test.ts
  packages/connect/src/messages/parseSignInURI.test.ts
  test/client/src/e2e.test.ts
  yarn.lock
Labels: chore

#41 feat: useSignInMessage hook
  .changeset/friendly-jeans-pay.md
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/src/hooks/useSignInMessage.ts
Labels: feature

#43 fix: export useSignInMessage
  packages/connect-kit/src/hooks/index.ts
Labels: bug

#42 chore: release packages
  .changeset/friendly-jeans-pay.md
  .changeset/six-eyes-grab.md
  .changeset/stale-carrots-wave.md
  apps/relay/CHANGELOG.md
  apps/relay/package.json
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect/CHANGELOG.md
  packages/connect/package.json
  test/client/CHANGELOG.md
  test/client/package.json
Labels: chore

#51 feat: hook/component callbacks
  .changeset/tidy-clouds-taste.md
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/src/components/Demo/Demo.tsx
  packages/connect-kit/src/hooks/useConnect.ts
  packages/connect-kit/src/hooks/useSignIn.ts
  packages/connect-kit/src/hooks/useVerifySignInMessage.ts
  packages/connect-kit/src/hooks/useWatchStatus.ts
Labels: feature

#52 chore: viem peer dependency
  .changeset/blue-trainers-pump.md
  packages/connect-kit/package.json
  packages/connect/package.json
Labels: chore

#50 feat: hoist siweUri and domain to config
  .changeset/weak-keys-admire.md
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect-kit/src/components/Demo/Demo.tsx
  packages/connect-kit/src/hooks/useConnect.ts
Labels: feature

#53 chore: publish packages
  .changeset/blue-trainers-pump.md
  .changeset/dry-cats-hug.md
  .changeset/tidy-clouds-taste.md
  .changeset/weak-keys-admire.md
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect/CHANGELOG.md
  packages/connect/package.json
Labels: chore

#68 chore: update relay URL
  examples/with-next-auth/pages/index.tsx
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
  packages/connect/CHANGELOG.md
  packages/connect/README.md
  packages/connect/package.json
  packages/connect/src/actions/app/connect.test.ts
  packages/connect/src/actions/app/status.test.ts
  packages/connect/src/actions/auth/authenticate.test.ts
  packages/connect/src/actions/auth/buildSignInMessage.test.ts
  packages/connect/src/actions/auth/parseSignInURI.test.ts
  packages/connect/src/clients/createAppClient.test.ts
  packages/connect/src/clients/createAuthClient.test.ts
  packages/connect/src/clients/createClient.test.ts
  packages/connect/src/clients/createClient.ts
  packages/connect/src/clients/transports/http.test.ts
Labels: chore

#71 feat: update docs
  README.md
  apps/relay/README.md
  packages/connect-kit/README.md
  packages/connect/README.md
Labels: feature

#77 fix: return nonce from connect
  .changeset/dull-rocks-clean.md
  apps/relay/src/handlers.ts
  apps/relay/src/server.test.ts
Labels: bug

#82 fix: Log in to Docker Hub to avoid rate limit errors
  .github/workflows/ci.yml
Labels: bug

#78 feat: optional relay
  .changeset/violet-poets-smell.md
  packages/connect-kit/src/components/ConnectKitProvider/ConnectKitProvider.tsx
Labels: feature

#86 fix: remove console.log
  packages/connect/src/messages/verify.ts
Labels: bug

#91 fix: remove link workaround
  packages/connect-kit/CHANGELOG.md
  packages/connect-kit/package.json
  packages/connect-kit/src/components/ConnectButton/ConnectButton.tsx
Labels: bug

#94 chore: update examples
  examples/frontend-only/package.json
  examples/frontend-only/src/App.tsx
  examples/frontend-only/yarn.lock
  examples/with-next-auth/package.json
  examples/with-next-auth/pages/api/auth/[...nextauth].ts
  examples/with-next-auth/pages/index.tsx
  examples/with-next-auth/yarn.lock
  packages/auth-client/CHANGELOG.md
  packages/auth-client/package.json
  packages/auth-client/src/messages/validate.test.ts
  packages/auth-client/src/messages/validate.ts
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
Labels: chore

#95 chore: update example app dependencies
  examples/frontend-only/package.json
  examples/frontend-only/yarn.lock
  examples/with-next-auth/package.json
  examples/with-next-auth/pages/api/auth/[...nextauth].ts
  examples/with-next-auth/yarn.lock
Labels: chore

#96 fix: ethers v5/v6 compatibility
  packages/auth-client/CHANGELOG.md
  packages/auth-client/package.json
  packages/auth-client/src/clients/ethereum/connector.ts
  packages/auth-client/src/clients/ethereum/ethers.ts
  packages/auth-client/src/clients/ethereum/viemConnector.ts
  packages/auth-client/src/messages/verify.ts
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
Labels: bug

#97 fix: ethers compatibility
  packages/auth-client/CHANGELOG.md
  packages/auth-client/package.json
  packages/auth-client/src/clients/ethereum/ethers.ts
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
Labels: bug

#98 fix: bundle ethers v6
  packages/auth-client/CHANGELOG.md
  packages/auth-client/package.json
  packages/auth-client/src/clients/ethereum/connector.ts
  packages/auth-client/src/clients/ethereum/ethers.ts
  packages/auth-client/src/clients/ethereum/viemConnector.ts
  packages/auth-client/src/messages/verify.ts
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  yarn.lock
Labels: bug

#100 chore: update demo apps
  examples/frontend-only/README.md
  examples/frontend-only/package.json
  examples/frontend-only/yarn.lock
  examples/with-next-auth/README.md
  examples/with-next-auth/package.json
  examples/with-next-auth/yarn.lock
Labels: chore

#101 chore: clean up stray renames
  README.md
  package.json
  packages/auth-client/README.md
  test/client/src/e2e.test.ts
Labels: chore

#103 fix: read nonce value from relay response
  .github/workflows/ci.yml
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  packages/auth-kit/src/hooks/useCreateChannel.ts
Labels: bug

#102 chore: add troubleshooting section to README
  packages/auth-kit/README.md
Labels: chore

#104 feat: update example apps
  examples/frontend-only/README.md
  examples/frontend-only/index.html
  examples/frontend-only/package.json
  examples/frontend-only/src/App.tsx
  examples/frontend-only/yarn.lock
  examples/with-next-auth/README.md
  examples/with-next-auth/package.json
  examples/with-next-auth/pages/index.tsx
  examples/with-next-auth/yarn.lock
Labels: feature

#107 feat: add checkout oneliners
  examples/frontend-only/package.json
  examples/frontend-only/src/App.tsx
  examples/frontend-only/yarn.lock
  examples/with-next-auth/package.json
  examples/with-next-auth/pages/index.tsx
  examples/with-next-auth/yarn.lock
Labels: feature

#109 feat: add sign out button
  .changeset/smart-kangaroos-cough.md
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
  packages/auth-kit/src/components/Button.tsx
  packages/auth-kit/src/components/Demo/Demo.tsx
  packages/auth-kit/src/components/FarcasterLogo.tsx
  packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
  packages/auth-kit/src/components/SignInButton/SignInButton.tsx
  packages/auth-kit/src/components/styles.css.ts
  packages/auth-kit/src/hooks/useCreateChannel.ts
  packages/auth-kit/src/hooks/useDetectClickOutside.ts
  packages/auth-kit/src/hooks/useSignIn.ts
  packages/auth-kit/src/hooks/useVerifySignInMessage.ts
  packages/auth-kit/src/hooks/useWatchStatus.ts
Labels: feature

#110 fix: allow port in domain
  .changeset/wise-horses-repeat.md
  apps/relay/src/schemas.ts
  apps/relay/src/server.test.ts
Labels: bug

#111 fix: memoize signin callbacks
  .changeset/friendly-impalas-speak.md
  packages/auth-kit/src/components/Demo/Demo.tsx
  packages/auth-kit/src/components/SignInButton/SignInButton.tsx
Labels: bug

#112 feat: add CSS classes to components
  .changeset/big-suns-confess.md
  packages/auth-kit/src/components/Dialog/Dialog.tsx
  packages/auth-kit/src/components/ProfileButton/ProfileButton.css.ts
  packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
  packages/auth-kit/src/components/QRCode.tsx
  packages/auth-kit/src/components/QRCodeDialog/QRCodeDialog.tsx
  packages/auth-kit/src/components/SignInButton/SignInButton.css.ts
  packages/auth-kit/src/components/SignInButton/SignInButton.tsx
  packages/auth-kit/src/components/SignOutButton/SignOutButton.css.ts
  packages/auth-kit/src/components/SignOutButton/SignOutButton.tsx
  packages/auth-kit/src/components/SignOutButton/index.ts
  packages/auth-kit/src/components/styles.css.ts
Labels: feature

#114 fix: handle reconnect on timeout
  .changeset/old-hotels-allow.md
  packages/auth-kit/src/components/Demo/Demo.tsx
  packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
  packages/auth-kit/src/components/SignOutButton/SignOutButton.tsx
  packages/auth-kit/src/hooks/useCreateChannel.ts
Labels: bug

#116 fix: iOS redirect delay
  .changeset/famous-glasses-exercise.md
  packages/auth-kit/src/components/Button.tsx
  packages/auth-kit/src/components/SignInButton/SignInButton.tsx
  packages/auth-kit/src/hooks/useSignIn.ts
  packages/auth-kit/src/hooks/useWatchStatus.ts
Labels: bug

#117 feat: add siweUri and host defaults
  .changeset/spicy-yaks-film.md
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
  packages/auth-kit/src/components/Demo/Demo.tsx
Labels: feature

#119 feat: return custody and verified addresses
  .changeset/itchy-stingrays-grab.md
  apps/relay/fastify.d.ts
  apps/relay/package.json
  apps/relay/src/addresses.ts
  apps/relay/src/env.ts
  apps/relay/src/handlers.ts
  apps/relay/src/server.test.ts
  apps/relay/src/server.ts
  packages/auth-client/src/actions/app/status.ts
  packages/auth-client/src/actions/app/watchStatus.ts
  test/client/src/e2e.test.ts
  yarn.lock
Labels: feature

#120 chore: release packages
  .changeset/big-suns-confess.md
  .changeset/famous-glasses-exercise.md
  .changeset/friendly-impalas-speak.md
  .changeset/itchy-stingrays-grab.md
  .changeset/old-hotels-allow.md
  .changeset/smart-kangaroos-cough.md
  .changeset/spicy-yaks-film.md
  .changeset/wise-horses-repeat.md
  apps/relay/CHANGELOG.md
  apps/relay/package.json
  packages/auth-client/CHANGELOG.md
  packages/auth-client/package.json
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  test/client/CHANGELOG.md
  test/client/package.json
Labels: chore

#122 feat: add verifications to profile
  packages/auth-client/README.md
  packages/auth-kit/README.md
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
  packages/auth-kit/src/components/Demo/Demo.tsx
  packages/auth-kit/src/components/SignOutButton/SignOutButton.css.ts
  packages/auth-kit/src/components/SignOutButton/SignOutButton.tsx
Labels: feature

#123 chore: add changeset
  .changeset/fuzzy-weeks-poke.md
Labels: chore

#124 fix: check for window.location
  .changeset/angry-hornets-divide.md
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
Labels: bug

#125 feat: make provider config optional
  .changeset/tiny-snails-burn.md
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
Labels: feature

#126 chore: version auth-kit
  .changeset/angry-hornets-divide.md
  .changeset/fuzzy-weeks-poke.md
  .changeset/plenty-steaks-lay.md
  .changeset/tiny-snails-burn.md
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
Labels: chore

#127 feat: sign out callback
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  packages/auth-kit/src/components/Demo/Demo.tsx
  packages/auth-kit/src/components/ProfileButton/ProfileButton.tsx
  packages/auth-kit/src/components/SignInButton/SignInButton.tsx
  packages/auth-kit/src/hooks/useWatchStatus.ts
Labels: feature

#128 fix: window conditional bug
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
Labels: bug

#129 fix: check with typeof
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/package.json
  packages/auth-kit/src/components/AuthKitProvider/AuthKitProvider.tsx
Labels: bug

#130 feat: update example apps with auth-kit@0.1.x
  examples/frontend-only/package.json
  examples/frontend-only/src/App.tsx
  examples/frontend-only/yarn.lock
  examples/with-next-auth/package.json
  examples/with-next-auth/pages/api/auth/[...nextauth].ts
  examples/with-next-auth/pages/index.tsx
  examples/with-next-auth/yarn.lock
Labels: feature

#131 fix: remove qrCodeUri
  packages/auth-kit/CHANGELOG.md
  packages/auth-kit/README.md
  packages/auth-kit/package.json
  packages/auth-kit/src/components/index.ts
  packages/auth-kit/src/hooks/useCreateChannel.ts
  packages/auth-kit/src/hooks/useSignIn.ts
Labels: bug
